# .github/workflows/build-cmake.yml
name: Build with CMake

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install MinGW
      run: |
        sudo apt update
        sudo apt install -y gcc-mingw-w64-x86-64 cmake
    
    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw-w64/Toolchain-mingw-x86_64.cmake ..
    
    - name: Build
      run: |
        cd build
        make
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: game.exe
        path: build/game.exe
